server:
  port: 6969
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: manager
    url: jdbc:h2:mem:testdb
    username: system
  jpa:
    properties:
      hibernate:
        show_sql: true
    defer-datasource-initialization: true