insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (101,'SNAP','Approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (102,'SNAP','Approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (103,'SNAP','Denied','Ishtiyaq','isti@123','High-icome');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (104,'SNAP','Denied','saurabh','saurabh@123','High-rent-icome');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (105,'CCAP','Approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (106,'CCAP','Approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (107,'CCAP','Denied','Ishtiyaq','isti@123','kids not available');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (108,'CCAP','Denied','saurabh','saurabh@123','kids age above 60');


insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (109,'Medicaid','Approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (110,'Medicaid','Approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (111,'Medicaid','Denied','Ishtiyaq','isti@123','High income');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (112,'Medicaid','Denied','saurabh','saurabh@123','High-property');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (113,'Medicare','Approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (114,'Medicare','Approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (115,'Medicare','Denied','Ishtiyaq','isti@123','Age above 65 yrs');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (116,'Medicare','Denied','saurabh','saurabh@123','Age not Approved');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (117,'QHP','Approved','Ishtiyaq','isti@123',100,'2022-05-13','2020-05-30');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,BENEFIT_AMT,START_DATE,END_DATE) values (118,'QHP','Approved','Saurabh','saurabh@123',100,'2022-05-13','2020-05-30');

insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (119,'QHP','Denied','Ishtiyaq','isti@123','High-icome');
insert into ELIGIBILITY_DTLS (ELIG_ID,PLAN_NAME,PLAN_STATUS,HOLDER_NAME,HOLDER_SSN,DENAIL_REASON) values (120,'QHP','Denied','saurabh','saurabh@123','High-icome');